### PR TITLE
fix: add info and step to run from scratch

### PR DESCRIPTION
**Pull request by glihm**
Some additional info to run from scratch.

### CODE REVIEW

**Comment by glihm** [comment]
@neotheprogramist actually we may also add in the cleanup something to de-init and re-init the submodules to ensure we can do a fresh run. WDYT?

**Comment by glihm** [comment]
@neotheprogramist pushed a proposal, let me know. :+1:

**Comment by neotheprogramist** [comment]
@glihm 
Cool, I approve the changes, nice improvement!

**Review by neotheprogramist — APPROVED** [review]
LGTM

**Pull request merged**
